development:
  adapter: postgresql
  database: charcutio_development
  pool: 5
  username: charcutio
  host: localhost
  encoding: utf8
  template: template0
test:
  adapter: postgresql
  database: charcutio_test
  pool: 5
  username: charcutio
  min_messages: warning
  encoding: utf8
  template: template0
